name: Pure Tungsten
rho: 19250.0 #kg/m3 density
cp: 134.0 #J/(kg.K) specific heat
k: 174.0 #W/(m.K) thermal conductivity
T_melt: 3695.0 #K melting temperature
T_boil: 5828.0 #K boiling temperature
L_fusion: 284000.0 #J/kg latent heat of fusion
dT_mushy: 80.0 #K mushy zone half-width
eta: 0.5 #absorptivity
eta_2D: 0.25 #calibrated 2D absorptivity
